# Stubs for pandas._libs.tslibs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=too-few-public-methods
from typing import Any


BaseOffset: Any


class _Tick:
    ...
