# Stubs for pandas._typing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,invalid-name
# pylint: disable=relative-beyond-top-level,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=blacklisted-name,c-extension-no-member,import-error
# pylint: disable=no-name-in-module

from pathlib import Path
from typing import Any, AnyStr, IO, TypeVar, Union

import numpy as np
from pandas._libs.tslibs import Timestamp
from pandas._libs.tslibs.period import Period
from pandas._libs.tslibs.timedeltas import Timedelta
from pandas.core.dtypes.generic import (
    ABCDataFrame,
    ABCExtensionArray,
    ABCIndexClass,
    ABCSeries,
    ABCSparseSeries,
)


AnyArrayLike = TypeVar(
    'AnyArrayLike',
    ABCExtensionArray,
    ABCIndexClass,
    ABCSeries,
    ABCSparseSeries,
    np.ndarray,
)
ArrayLike = TypeVar('ArrayLike', ABCExtensionArray, np.ndarray)
DatetimeLikeScalar = TypeVar(
    'DatetimeLikeScalar', Period, Timestamp, Timedelta)
Dtype: Any
FilePathOrBuffer = str | Path | IO[AnyStr]
FrameOrSeries = TypeVar('FrameOrSeries', ABCSeries, ABCDataFrame)
Scalar = str | int | float
Axis = str | int
