# Stubs for pandas.core.internals.arrays (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,multiple-statements
from typing import Any


def extract_array(obj: Any, extract_numpy: bool = ...) -> Any: ...
