# Stubs for pandas.core.arrays._ranges (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,invalid-name
# pylint: disable=relative-beyond-top-level,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Tuple

import numpy as np
from pandas._libs.tslibs import Timestamp
from pandas.tseries.offsets import DateOffset


def generate_regular_range(
        start: Timestamp, end: Timestamp,
        periods: int, freq: DateOffset) -> Tuple[np.ndarray, str]:
    ...
