# Stubs for pandas.core.arrays.array_ (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,invalid-name
# pylint: disable=relative-beyond-top-level,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin

from typing import Optional, Sequence, Union

import numpy as np
from pandas.core.dtypes.dtypes import ExtensionDtype
from pandas.core.dtypes.generic import ABCExtensionArray


def array(
        data: Sequence[object],
        dtype: Optional[Union[str, np.dtype, ExtensionDtype]] = ...,
        copy: bool = ...) -> ABCExtensionArray:
    ...
