# Stubs for pandas.core.dtypes.concat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,invalid-name
# pylint: disable=relative-beyond-top-level,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias

from typing import Any


def get_dtype_kinds(v: Any) -> Any:
    ...


def union_categoricals(
        to_union: Any, sort_categories: bool = ...,
        ignore_order: bool = ...) -> Any:
    ...
