# Stubs for pandas.core.index (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,invalid-name
# pylint: disable=relative-beyond-top-level,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias,signature-differs
# pylint: disable=no-name-in-module
from pandas.core.indexes.api import _all_indexes_same as _all_indexes_same
from pandas.core.indexes.api import _get_combined_index as _get_combined_index
from pandas.core.indexes.api import (
    _get_consensus_names as _get_consensus_names,
)
from pandas.core.indexes.api import (
    _get_objs_combined_axis as _get_objs_combined_axis,
)
from pandas.core.indexes.api import _new_Index as _new_Index
from pandas.core.indexes.api import _union_indexes as _union_indexes
from pandas.core.indexes.api import CategoricalIndex as CategoricalIndex
from pandas.core.indexes.api import DatetimeIndex as DatetimeIndex
from pandas.core.indexes.api import ensure_index as ensure_index
from pandas.core.indexes.api import (
    ensure_index_from_sequences as ensure_index_from_sequences,
)
from pandas.core.indexes.api import Float64Index as Float64Index
from pandas.core.indexes.api import Index as Index
from pandas.core.indexes.api import Int64Index as Int64Index
from pandas.core.indexes.api import IntervalIndex as IntervalIndex
from pandas.core.indexes.api import InvalidIndexError as InvalidIndexError
from pandas.core.indexes.api import MultiIndex as MultiIndex
from pandas.core.indexes.api import NaT as NaT
from pandas.core.indexes.api import NumericIndex as NumericIndex
from pandas.core.indexes.api import PeriodIndex as PeriodIndex
from pandas.core.indexes.api import RangeIndex as RangeIndex
from pandas.core.indexes.api import TimedeltaIndex as TimedeltaIndex
from pandas.core.indexes.api import UInt64Index as UInt64Index
from pandas.core.indexes.multi import _sparsify as _sparsify
