# Stubs for pandas._config (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-import,useless-import-alias

from pandas._config import config as config
from pandas._config.config import describe_option as describe_option
from pandas._config.config import get_option as get_option
from pandas._config.config import option_context as option_context
from pandas._config.config import options as options
from pandas._config.config import reset_option as reset_option
from pandas._config.config import set_option as set_option
from pandas._config.display import (
    detect_console_encoding as detect_console_encoding,
)
