# Stubs for pandas.core.reshape.api (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-import,useless-import-alias

from pandas.core.reshape.concat import concat as concat
from pandas.core.reshape.melt import lreshape as lreshape
from pandas.core.reshape.melt import melt as melt
from pandas.core.reshape.melt import wide_to_long as wide_to_long
from pandas.core.reshape.merge import merge as merge
from pandas.core.reshape.merge import merge_asof as merge_asof
from pandas.core.reshape.merge import merge_ordered as merge_ordered
from pandas.core.reshape.pivot import crosstab as crosstab
from pandas.core.reshape.pivot import pivot as pivot
from pandas.core.reshape.pivot import pivot_table as pivot_table
from pandas.core.reshape.tile import cut as cut
from pandas.core.reshape.tile import qcut as qcut
