# Stubs for pandas.util._exceptions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,invalid-name
# pylint: disable=relative-beyond-top-level,arguments-differ
# pylint: disable=no-member
from typing import Any


def rewrite_exception(old_name: Any, new_name: Any) -> None:
    ...
