# Stubs for pandas.util._print_versions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,invalid-name
# pylint: disable=relative-beyond-top-level,arguments-differ
# pylint: disable=no-member
from typing import Any


def get_sys_info() -> Any:
    ...


def show_versions(as_json: bool = ...) -> None:
    ...


def main() -> Any:
    ...
