# Stubs for pandas.util._tester (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,invalid-name
# pylint: disable=relative-beyond-top-level,arguments-differ
# pylint: disable=no-member
from typing import Any, Optional


def test(extra_args: Optional[Any] = ...) -> None:
    ...
