# Stubs for pandas.core.computation.api (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=redefined-builtin,unused-import,useless-import-alias
from pandas.core.computation.eval import eval as eval
