# Stubs for pandas.io.json (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-argument,redefined-outer-name,invalid-name
# pylint: disable=relative-beyond-top-level,arguments-differ
# pylint: disable=no-member,too-few-public-methods,keyword-arg-before-vararg
# pylint: disable=super-init-not-called,abstract-method,redefined-builtin
# pylint: disable=unused-import,useless-import-alias

from pandas.io.json._json import dumps as dumps
from pandas.io.json._json import loads as loads
from pandas.io.json._json import read_json as read_json
from pandas.io.json._json import to_json as to_json
from pandas.io.json._normalize import json_normalize as json_normalize
from pandas.io.json._table_schema import (
    build_table_schema as build_table_schema,
)
