# Stubs for pandas.plotting (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-import,useless-import-alias

from pandas.plotting._core import boxplot as boxplot
from pandas.plotting._core import boxplot_frame as boxplot_frame
from pandas.plotting._core import (
    boxplot_frame_groupby as boxplot_frame_groupby,
)
from pandas.plotting._core import hist_frame as hist_frame
from pandas.plotting._core import hist_series as hist_series
from pandas.plotting._core import PlotAccessor as PlotAccessor
from pandas.plotting._misc import andrews_curves as andrews_curves
from pandas.plotting._misc import autocorrelation_plot as autocorrelation_plot
from pandas.plotting._misc import bootstrap_plot as bootstrap_plot
from pandas.plotting._misc import (
    deregister as deregister_matplotlib_converters,
)
from pandas.plotting._misc import lag_plot as lag_plot
from pandas.plotting._misc import parallel_coordinates as parallel_coordinates
from pandas.plotting._misc import plot_params as plot_params
from pandas.plotting._misc import radviz as radviz
from pandas.plotting._misc import register as register_matplotlib_converters
from pandas.plotting._misc import scatter_matrix as scatter_matrix
from pandas.plotting._misc import table as table
