# Stubs for pandas.api.extensions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.
# pylint: disable=unused-import,useless-import-alias

"""Public API for extending pandas objects."""
from pandas.core.accessor import (
    register_dataframe_accessor as register_dataframe_accessor,
)
from pandas.core.accessor import (
    register_index_accessor as register_index_accessor,
)
from pandas.core.accessor import (
    register_series_accessor as register_series_accessor,
)
from pandas.core.algorithms import take as take
from pandas.core.arrays import ExtensionArray as ExtensionArray
from pandas.core.arrays import (
    ExtensionScalarOpsMixin as ExtensionScalarOpsMixin,
)
from pandas.core.dtypes.dtypes import ExtensionDtype as ExtensionDtype
from pandas.core.dtypes.dtypes import (
    register_extension_dtype as register_extension_dtype,
)
